### ISSUE TITLE
Performance regression in `prep_perims()`

### ISSUE THREAD

**Issue by CoryMcCartan** [alarm-redist/redistmetrics#19]
A 3-4k precinct map wasn't done with `prep_perims(..., ncores=8)` in 20+ minutes and chewed up 15+ GB of RAM

By comparison, `redist.prep.polsbypopper(..., ncores=4)` from `redist` rev 3e3bebd completed in a few seconds and dozens of MB of RAM

(the final prepped perim file is just 185 kb)

**Comment by christopherkenny** [comment]
This seems to have been some weird blip, as it can't be reproduced and the (quite old but still) new `prep_perims()` is ~10x faster, while using ~1/4 of the memory.
