### ISSUE TITLE
Administrative Splits

### ISSUE THREAD

**Issue by christopherkenny** [alarm-redist/redistmetrics#2]
@CoryMcCartan had a vision for some outputs for splits, primarily options to focus on counts of counties split and counts of districts split.

**Comment by CoryMcCartan** [comment]
yeah maybe just in the C++ a function to count the number of times each admin unit is split 

then we can use that to compute total splits, # which are split 1+ times, 2+ times, etc

**Comment by christopherkenny** [comment]
@CoryMcCartan, see `splits_count()`
